# Generated by Django 3.2 on 2022-04-11 06:33

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_articlemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='content',
            field=ckeditor.fields.RichTextField(default='blank'),
        ),
        migrations.CreateModel(
            name='commentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(default='blank')),
                ('first_published', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.articlemodel')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
